services:
  monster-generator-json-schema:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONSTER_KIND=werewolf
    volumes:
      # this allows to use devcontainer and it will work outside of it too
      - ${LOCAL_WORKSPACE_FOLDER:-.}${LOCAL_WORKSPACE_FOLDER:+/monster-generator}/contents:/app/contents

    models:
      qwen2_5:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_CHAT_MODEL
      
models:
  qwen2_5:
    model: ai/qwen2.5:latest
